nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.0.cjs
supportedArchitectures:
  os: [linux, darwin]
  cpu: [x64, arm64]
enableScripts: false
dependenciesMeta:
  hugo-bin-extended:
    built: true
